import asyncio
from copy import deepcopy
import json
from typing import Any, Optional

from common import get_logger, get_model_registry
from common.config_utils import get_base_config
from common.error_codes import ErrorCodes
from common.exceptions import ExtractionError
from rag.ingestion.extractor.llm_extractor import LLMExtractor
from rag.ingestion.extractor.metadata_creator import MetadataCreator
from rag.ingestion.extractor.rdb_builder import RdbBuilder
from rag.ingestion.extractor.rule_extractor import RuleExtractor
from rag.ingestion.extractor.clause_forest_builder import ClauseForestBuilder
from rag.ingestion.utils.confidence_calculator import ConfidenceCalculator
from rag.ingestion.extractor.validator import check_missing_fields

logger = get_logger(__name__)


class Extractor:
    """
    Multi-strategy extraction pipeline: rule-based + LLM-based extraction
    Documents generated by agents will be parsed by rule-based extraction first, then the missing fields are extracted by LLM
    """

    def __init__(self, model: dict[str, Any], schema_path: str) -> None:
        with open(schema_path, "r") as f:
            self.schema: dict[str, Any] = json.load(f)

        self.llm_extractor: LLMExtractor = LLMExtractor(model)
        self.confidence_calculator: ConfidenceCalculator = ConfidenceCalculator()
        self.metadata_creator = MetadataCreator()

    def extract(
        self, documents: list[dict[str, Any]], source_file: str = None
    ) -> tuple[dict[str, Any], dict[str, Any], int, Any]:
        """
        Args:
            documents: list of documents, format: [dict[str, Any], ...]
            source_file: optional source file name for database storage
        Returns:
            tuple[dict[str, Any], dict[str, Any], int, ClauseNode]: confidence_result, metadata, llm_tokens, clause_tree
        """
        if not isinstance(documents, list) or not all(isinstance(doc, dict) for doc in documents):
            raise ExtractionError(
                message="Invalid input: documents must be a list of dict objects",
                code=ErrorCodes.S_INGESTION_003,
                details={"input_type": type(documents).__name__},
            )

        try:
            logger.info("Starting rule-based extraction")

            raw_documents = deepcopy(documents)
            rule_extractor: RuleExtractor = RuleExtractor(self.schema)
            extracted_results = rule_extractor.extract(raw_documents)

            missing_fields = check_missing_fields(self.schema, extracted_results)

            llm_tokens = 0
            if missing_fields:
                llm_results = self._fallback_to_llm_extraction(documents[:2], extracted_results, missing_fields)
                if llm_results:
                    extracted_results = llm_results["content"]
                    llm_tokens = llm_results.get("tokens", 0)

            logger.info("Calculating confidence scores")
            confidence_result = self.confidence_calculator.calculate(
                extracted_results,
                self.schema,
                rule_extractor.extraction_signals,
            )
            metadata = self.metadata_creator.create(extracted_results)

            # Extract clause tree structure
            logger.info("Extracting clause trees from documents")
            clause_forest_builder = ClauseForestBuilder()
            clause_forest = clause_forest_builder.build(raw_documents)

            # Build entities and save to database
            rdb_builder = RdbBuilder(
                schema=self.schema,
                extracted_results=extracted_results,
                confidence_score=confidence_result.get("overall_confidence", 0.0),
                source_file=source_file,
            )
            rdb_builder.build()

            return confidence_result, metadata, llm_tokens, clause_forest

        except ExtractionError:
            raise
        except Exception as e:
            # Wrap other exceptions
            raise ExtractionError(
                message=f"Extraction pipeline failed: {str(e)}",
                code=ErrorCodes.S_INGESTION_003,
                details={"error": str(e)},
            ) from e

    async def aextract(
        self, documents: list[dict[str, Any]], source_file: str = None
    ) -> tuple[dict[str, Any], dict[str, Any], int, Any]:
        """Async version of extract. LLM calls use native async, CPU-bound work runs in thread pool."""
        if not isinstance(documents, list) or not all(isinstance(doc, dict) for doc in documents):
            raise ExtractionError(
                message="Invalid input: documents must be a list of dict objects",
                code=ErrorCodes.S_INGESTION_003,
                details={"input_type": type(documents).__name__},
            )

        try:
            logger.info("Starting rule-based extraction (async)")

            raw_documents = deepcopy(documents)
            rule_extractor: RuleExtractor = RuleExtractor(self.schema)
            # Rule extraction is CPU-bound (regex + BeautifulSoup)
            extracted_results = await asyncio.to_thread(rule_extractor.extract, raw_documents)

            missing_fields = check_missing_fields(self.schema, extracted_results)

            llm_tokens = 0
            if missing_fields:
                llm_results = await self._afallback_to_llm_extraction(documents[:2], extracted_results, missing_fields)
                if llm_results:
                    extracted_results = llm_results["content"]
                    llm_tokens = llm_results.get("tokens", 0)

            logger.info("Calculating confidence scores")
            confidence_result = self.confidence_calculator.calculate(
                extracted_results,
                self.schema,
                rule_extractor.extraction_signals,
            )
            metadata = self.metadata_creator.create(extracted_results)

            # Clause forest building is CPU-bound (markdown parsing + regex)
            logger.info("Extracting clause trees from documents")
            clause_forest_builder = ClauseForestBuilder()
            clause_forest = await asyncio.to_thread(clause_forest_builder.build, raw_documents)

            # DB writes
            rdb_builder = RdbBuilder(
                schema=self.schema,
                extracted_results=extracted_results,
                confidence_score=confidence_result.get("overall_confidence", 0.0),
                source_file=source_file,
            )
            await asyncio.to_thread(rdb_builder.build)

            return confidence_result, metadata, llm_tokens, clause_forest

        except ExtractionError:
            raise
        except Exception as e:
            raise ExtractionError(
                message=f"Extraction pipeline failed: {str(e)}",
                code=ErrorCodes.S_INGESTION_003,
                details={"error": str(e)},
            ) from e

    def _fallback_to_llm_extraction(
        self,
        documents: list[dict[str, Any]],
        extracted_results: dict[str, Any],
        missing_fields: dict[str, Any],
    ) -> Optional[dict[str, Any]]:

        logger.warning(f"Missing fields detected: {missing_fields}. ")

        try:
            hints = extracted_results

            content = "\n".join([doc.get("text", "") for doc in documents])

            llm_results = self.llm_extractor.extract(content, hints=hints, missing_fields=missing_fields)
            logger.info("LLM extraction completed")
            return llm_results

        except Exception as e:
            logger.error(f"LLM extraction failed: {e}", exc_info=True)
            return None

    async def _afallback_to_llm_extraction(
        self,
        documents: list[dict[str, Any]],
        extracted_results: dict[str, Any],
        missing_fields: dict[str, Any],
    ) -> Optional[dict[str, Any]]:
        """Async version using LLM's native agenerate()."""
        logger.warning(f"Missing fields detected: {missing_fields}. ")

        try:
            hints = extracted_results
            content = "\n".join([doc.get("text", "") for doc in documents])

            llm_results = await self.llm_extractor.aextract(content, hints=hints, missing_fields=missing_fields)
            logger.info("LLM extraction completed (async)")
            return llm_results

        except Exception as e:
            logger.error(f"LLM extraction failed: {e}", exc_info=True)
            return None


def _create_extractor() -> Extractor:
    schema_path = get_base_config("schema_path", None)
    registry = get_model_registry()
    model_config = registry.get_chat_model("qwen_32B")
    return Extractor(model=model_config.to_dict(), schema_path=schema_path)


extractor = _create_extractor()


if __name__ == "__main__":
    from pathlib import Path

    with open(Path(__file__).parent / "data" / "policy_base.json", "r") as f:
        policy_base_1 = json.load(f)
    extractor = _create_extractor()
    extractor.extract(policy_base_1["pages"], source_file="policy_base.json")
