apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-model-cache
  namespace: production
  labels:
    app.kubernetes.io/name: rag-fintech
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: alibabacloud-cnfs-nas
  resources:
    requests:
      storage: 30Gi
